// supabase/functions/write-news/models/news.ts

export interface RawNews {
	id: string;
	url: string;
	title?: string;
	publication_date?: string | Date;
	source_name?: string;
	source_type: string;
	source_id?: string;
	discovered_at?: string | Date;
	context?: any;
	plaintext?: string;
	status: 'pending' | 'processing' | 'processed' | 'error';
	processed_news_id?: string;
	process_attempts?: number;
	last_attempt_at?: string | Date;
	error?: string;
	source_fomo?: number;
	editor_notes?: string;
}

export interface ProcessedNews {
	id?: string; // UUID will be generated by Supabase
	submission_id?: number;
	title: string;
	url: string;
	source?: string;
	read_time?: number;
	fomo_score?: number;
	tags?: string[];
	week_id?: number;
	entities?: any;
	context?: any;
	impact_score?: number;
	publication_date?: string | Date;
	viral_title?: string;
	slug?: string;
	summary?: string;
	seo?: {
		title?: string;
		keywords?: string[];
		image_url?: string;
		description?: string;
		article_type?: string;
		canonical_url?: string;
	};
	created_at?: string | Date;
	processed_at?: string | Date;
}

export interface ProcessingResult {
	success: boolean;
	raw_news_id: string;
	processed_news_id?: string;
	slug?: string;
	error?: string;
}